/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

typedef volatile unsigned int vuint32_t;
#include<stdint.h>

#define Base_Rcc     0x40021000
#define Base_GPIOPA  0x40010800

#define RCC_APB2ENR   *(volatile uint32_t*) (Base_Rcc + 0x18)
#define GOIO_CRH      *(volatile uint32_t*) (Base_GPIOPA + 0x04)
#define GPIO_ODR      *(volatile uint32_t*) (Base_GPIOPA + 0x0c)

typedef union
{
	vuint32_t all_fields;
	struct
	{
		vuint32_t reserved:13;
		vuint32_t p_13:1;

	}pin;	
}R_ODR_t ;

volatile R_ODR_t * R_ODR =(volatile R_ODR_t*)(Base_GPIOPA + 0x0c);

unsigned char g_value[3] = {1, 2, 3};
unsigned char const_vaariables[3] = {1, 2, 3};
int main(void)
{
	RCC_APB2ENR |= 1<<2;
	GOIO_CRH    &= 0xFF0FFFFF;
	GOIO_CRH    |= 0x00200000;

	while(1)
	{
		R_ODR->pin.p_13 = 1;
		for(int i = 0; i < 5000; i++);

		R_ODR->pin.p_13 = 0;
		for(int i = 0; i < 5000; i++);
	}
	return 0;
}
